Document: uniscan
Title: Debian uniscan Manual
Author: <insert document author here>
Abstract: This manual describes what uniscan is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uniscan/uniscan.sgml.gz

Format: postscript
Files: /usr/share/doc/uniscan/uniscan.ps.gz

Format: text
Files: /usr/share/doc/uniscan/uniscan.text.gz

Format: HTML
Index: /usr/share/doc/uniscan/html/index.html
Files: /usr/share/doc/uniscan/html/*.html
